#pragma once

#define NUM_MIDI_KEYBOARD_KEYS 88

#define NUM_VERTICES_PER_KEY 4
#define NUM_DIMENSIONS_PER_VERTEX 3
#define NUM_COLOR_CHANNELS_PER_VERTEX 3
#define NUM_DIMENSIONS_PER_UV 2

#define NUM_ELEMENTS_PER_VERTEX (NUM_VERTICES_PER_KEY * NUM_DIMENSIONS_PER_VERTEX)
#define NUM_ELEMENTS_PER_INDEX 6
#define NUM_ELEMENTS_PER_TEXTURE_UV (NUM_VERTICES_PER_KEY * NUM_DIMENSIONS_PER_UV)
#define NUM_ELEMENTS_PER_COLOR (NUM_VERTICES_PER_KEY * NUM_COLOR_CHANNELS_PER_VERTEX)